# Site settings
name: Vanessa Colina
title: Vanessa Colina | Product Designer
description: Product designer with an entrepreneurial mindset focused on creating experiences that respond to market needs.
url: http://www.vanessacolina.com
baseurl: ''
email: info@vanessacolina.com
cover: 
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: 
social:
  - title: email
    url: mailto:info@vanessacolina.com
  - title: twitter
    url: https://twitter.com/vcolinau
  - title: linkedin
    url: https://www.linkedin.com/in/vanessacolina/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
